# This file was generated by GoReleaser. DO NOT EDIT.
cask "movcaster" do
  version "0.9.0"

  on_macos do
    on_intel do
      sha256 "6305cc94bfd2c43d7b6652749051a2a04fc320fa5ebe176ee8fa6e2ba6b096fd"
      url "https://github.com/juliocesar/movcaster/releases/download/v#{version}/movcaster_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "f95090d12731c1e5127f52fcbc83e3dfcdc809de2eaa4fb0e921059917200962"
      url "https://github.com/juliocesar/movcaster/releases/download/v#{version}/movcaster_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "532a64410f50f86ef8c84680af0b5e985dd4a615c895b042ae1b3e763956a3e6"
      url "https://github.com/juliocesar/movcaster/releases/download/v#{version}/movcaster_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "7688d194063fc4257bfcb885185669bdec123cad8dbcf9ab5ee09a15fbc1badc"
      url "https://github.com/juliocesar/movcaster/releases/download/v#{version}/movcaster_linux_arm64.tar.gz"
    end
  end

  name "movcaster"
  desc "Stream local video to a DLNA renderer (LG webOS TV) from the terminal"
  homepage "https://github.com/juliocesar/movcaster"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "ffmpeg",
    ]

  binary "movcaster"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/movcaster"]
    end
  end

  # No zap stanza required

end
