# This file was generated by GoReleaser. DO NOT EDIT.
cask "movcaster" do
  version "0.5.0"

  on_macos do
    on_intel do
      sha256 "bb560e2fdecc5ff8ebb31b9d8840c1fb32bca4dfe1a58e08a6201f45311938b1"
      url "https://github.com/juliocesar/movcaster/releases/download/v#{version}/movcaster_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "e161d2d2c2153caf3f7691a0cdf5dc38058150c3cff1e0ae762fad8366d7bb53"
      url "https://github.com/juliocesar/movcaster/releases/download/v#{version}/movcaster_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "5780298899af388103d45bcd9fcaf1fcc8537e5f453fc0d72ccf19d044f804f7"
      url "https://github.com/juliocesar/movcaster/releases/download/v#{version}/movcaster_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "7a5358c85914019eff2025b3e7a630612ba6f8ec1a84eb1f37774fed3335bb8c"
      url "https://github.com/juliocesar/movcaster/releases/download/v#{version}/movcaster_linux_arm64.tar.gz"
    end
  end

  name "movcaster"
  desc "Stream local video to a DLNA renderer (LG webOS TV) from the terminal"
  homepage "https://github.com/juliocesar/movcaster"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "ffmpeg",
    ]

  binary "movcaster"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/movcaster"]
    end
  end

  # No zap stanza required

end
