# This file was generated by GoReleaser. DO NOT EDIT.
cask "movcaster" do
  version "0.2.1"

  on_macos do
    on_intel do
      sha256 "eddbdbb42ea9c709e67d2b45dbcd6e4520f8c2f124837ce953ed44350be9b130"
      url "https://github.com/juliocesar/movcaster/releases/download/v#{version}/movcaster_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "a61c1fb675c654077804a670a602366faa0b05a52151ddcca8416ee2f8d27c42"
      url "https://github.com/juliocesar/movcaster/releases/download/v#{version}/movcaster_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "40afbdace530059645c8409c98676be824147ffe3ec4a2925591ce888a4c4737"
      url "https://github.com/juliocesar/movcaster/releases/download/v#{version}/movcaster_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "716e0a391664565e87c98581fe0afc9302f83e550d46db159d7f01a6559cff80"
      url "https://github.com/juliocesar/movcaster/releases/download/v#{version}/movcaster_linux_arm64.tar.gz"
    end
  end

  name "movcaster"
  desc "Stream local video to a DLNA renderer (LG webOS TV) from the terminal"
  homepage "https://github.com/juliocesar/movcaster"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "ffmpeg",
    ]

  binary "movcaster"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/movcaster"]
    end
  end

  # No zap stanza required

end
